@startuml
start

repeat

:development
(one or several tickets
from the board are implemented
and merged to //improvements//);

repeat
  :branch //improvements//
  is ready for release;

  note right
    //nttt/_version.py// has version //a.b.c-SNAPSHOT//
  end note

  repeat
    :developer testing of code
    from //improvements// is performed;
    backward: fix bugs in //improvements//;
  repeat while (bugs found?) is (yes)
  ->no;
  :put version //a.b.c// in //nttt/_version.py//;

  :create release //**va.b.c**//
  from branch //improvements//;

  :increment version in //improvements//:
  put //x.y.z-SNAPSHOT// in //nttt/_version.py//;

  :customer testing of
  release //va.b.c//;

  backward: fix the bugs in //improvements//;
repeat while (bugs found?) is (yes)
->no;

repeat while

@enduml